# Generated by Django 3.2.5 on 2021-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
